DROP TABLE CCHAPMAN6.COH_EMR_SHLDR;
CREATE TABLE CCHAPMAN6.COH_EMR_SHLDR AS 
SELECT a.*, b.code_desc
FROM MSCHROEDER5.CDM_EMR_DIAG_MINI a 
INNER JOIN CCHAPMAN6.ICD_DX_SHLDR b
ON a.DX = b.CODE_FMT AND a.DX_TYPE = b.CODE_TYPE;

CREATE TABLE CCHAPMAN6.F_COHORT_CDM_ALL AS
SELECT DISTINCT * FROM 
(SELECT * FROM MSCHROEDER5.F_COHORT_CDM_11_15
    UNION ALL
SELECT * FROM MSCHROEDER5.F_COHORT_CDM_13_17);

SELECT COUNT(1) FROM CCHAPMAN6.F_COHORT_CDM_ALL
UNION ALL
SELECT COUNT(DISTINCT PATID) FROM CCHAPMAN6.F_COHORT_CDM_ALL
UNION ALL
SELECT COUNT(DISTINCT PATID) FROM MSCHROEDER5.F_COHORT_CDM_11_15
UNION ALL
SELECT COUNT(DISTINCT PATID) FROM MSCHROEDER5.F_COHORT_CDM_13_17
UNION ALL
SELECT COUNT(DISTINCT PATID) FROM MSCHROEDER5.CDM_EMR_DIAG_MINI;

DROP TABLE CCHAPMAN6.F_COHORT_CDM_ALL;

DROP TABLE CCHAPMAN6.COH_EMR_SHLDR_POST_BC;
CREATE TABLE CCHAPMAN6.COH_EMR_SHLDR_POST_BC AS
SELECT a.PATID, a.ENC_TYPE AS SHLDR_ENC_TYPE, 
    a.ADMIT_DATE AS SHLDR_DX_DATE, 
    a.PROVIDERID AS SHLDR_PRVDR, 
    a.DX AS SHLDR_DX, a.DX_TYPE, a.DX_SOURCE, a. DX_ORIGIN, a.SITE_SCHEMA, a.CODE_DESC, 
    b.SITE AS BC_SITE, b.DXDATE AS BC_DX_DATE, 
    b.STAGE AS BC_STAGE, b.CLASSCASE AS BC_CLASSCASE
FROM CCHAPMAN6.COH_EMR_SHLDR a 
INNER JOIN MSCHROEDER5.F_COHORT_CDM_11_15 b
ON a.PATID = b.PATID
WHERE b.DXDATE - a.ADMIT_DATE >= 730;

SELECT COUNT(DISTINCT PATID) FROM CCHAPMAN6.COH_EMR_SHLDR_POST_BC 
UNION ALL
SELECT COUNT(1) FROM CCHAPMAN6.COH_EMR_SHLDR_POST_BC;

DROP TABLE CCHAPMAN6.COH_EMR_SHLDR_BC_CMS;
CREATE TABLE CCHAPMAN6.COH_EMR_SHLDR_BC_CMS AS
SELECT a.PATID, a.ENC_TYPE AS SHLDR_ENC_TYPE, 
    a.ADMIT_DATE AS SHLDR_DX_DATE, 
    a.PROVIDERID AS SHLDR_PRVDR, 
    a.DX AS SHLDR_DX, a.DX_TYPE, a.DX_SOURCE, a. DX_ORIGIN, a.SITE_SCHEMA, a.CODE_DESC, 
    b.SITE AS BC_SITE, b.DXDATE AS BC_DX_DATE, 
    b.STAGE AS BC_STAGE, b.CLASSCASE AS BC_CLASSCASE
FROM CCHAPMAN6.COH_EMR_SHLDR a 
INNER JOIN MSCHROEDER5.F_COHORT_CDM_11_15_2154 b
ON a.PATID = b.PATID
WHERE b.DXDATE - a.ADMIT_DATE >= 730;

SELECT COUNT(DISTINCT PATID) FROM CCHAPMAN6.COH_EMR_SHLDR_BC_CMS;